### ISSUE TITLE
Link on the homepage still reads 'French Toast'

### ISSUE THREAD

**Issue by huetrashme0947** [Kometro/odin-recipes#1]
Although the issue of [`recipes/frenchtoast.html`](https://github.com/Kometro/odin-recipes/blob/6b5ff5f0c9f9f945605b5826ae5e11ba5e9d7c2f/recipes/frenchtoast.html#L8) displaying 'French Fries' instead of 'French Toast' prior to commit #735a995 was fixed, [`index.html`](https://github.com/Kometro/odin-recipes/blob/e05a7af451a63de98b13974d00d9dd1723b34849/index.html#L12) still displays the old name 'French Fries'.

**Comment by Kometro** [comment]
"French Fries" was corrected to "French Toast" with commit #2ec4b65
